// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taskflowv1/task_events.proto

package taskflowv1

import (
	reflect "reflect"
	sync "sync"

	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskflow_v1_task_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SubscribeRequest) ProtoMessage()    {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskflow_v1_task_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_taskflow_v1_task_events_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type TaskEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ProjectId    string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	BoardId      string                 `protobuf:"bytes,4,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	TaskId       string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ActorId      string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	FromStatusId string                 `protobuf:"bytes,7,opt,name=from_status_id,json=fromStatusId,proto3" json:"from_status_id,omitempty"`
	ToStatusId   string                 `protobuf:"bytes,8,opt,name=to_status_id,json=toStatusId,proto3" json:"to_status_id,omitempty"`
	OccurredAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	PayloadJson  string                 `protobuf:"bytes,10,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskflow_v1_task_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskEvent) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TaskEvent) ProtoMessage()    {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_taskflow_v1_task_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_taskflow_v1_task_events_proto_rawDescGZIP(), []int{1}
}

func (x *TaskEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *TaskEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}
func (x *TaskEvent) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}
func (x *TaskEvent) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}
func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}
func (x *TaskEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}
func (x *TaskEvent) GetFromStatusId() string {
	if x != nil {
		return x.FromStatusId
	}
	return ""
}
func (x *TaskEvent) GetToStatusId() string {
	if x != nil {
		return x.ToStatusId
	}
	return ""
}
func (x *TaskEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}
func (x *TaskEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

var File_taskflow_v1_task_events_proto protoreflect.FileDescriptor

func strptr(v string) *string { return &v }
func i32ptr(v int32) *int32   { return &v }
func boolptr(v bool) *bool    { return &v }
func labelptr(v descriptorpb.FieldDescriptorProto_Label) *descriptorpb.FieldDescriptorProto_Label {
	return &v
}
func typeptr(v descriptorpb.FieldDescriptorProto_Type) *descriptorpb.FieldDescriptorProto_Type {
	return &v
}

func makeTaskEventsRawDescriptor() []byte {
	optional := descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL
	stringType := descriptorpb.FieldDescriptorProto_TYPE_STRING
	messageType := descriptorpb.FieldDescriptorProto_TYPE_MESSAGE
	field := func(name, jsonName string, number int32, typ descriptorpb.FieldDescriptorProto_Type, typeName string) *descriptorpb.FieldDescriptorProto {
		f := &descriptorpb.FieldDescriptorProto{Name: strptr(name), JsonName: strptr(jsonName), Number: i32ptr(number), Label: labelptr(optional), Type: typeptr(typ)}
		if typeName != "" {
			f.TypeName = strptr(typeName)
		}
		return f
	}
	fd := &descriptorpb.FileDescriptorProto{
		Name:       strptr("taskflowv1/task_events.proto"),
		Package:    strptr("taskflow.v1"),
		Dependency: []string{"google/protobuf/timestamp.proto"},
		Syntax:     strptr("proto3"),
		Options:    &descriptorpb.FileOptions{GoPackage: strptr("github.com/example/taskflow/backend/proto/taskflowv1")},
		MessageType: []*descriptorpb.DescriptorProto{
			{Name: strptr("SubscribeRequest"), Field: []*descriptorpb.FieldDescriptorProto{field("project_id", "projectId", 1, stringType, "")}},
			{Name: strptr("TaskEvent"), Field: []*descriptorpb.FieldDescriptorProto{
				field("id", "id", 1, stringType, ""),
				field("type", "type", 2, stringType, ""),
				field("project_id", "projectId", 3, stringType, ""),
				field("board_id", "boardId", 4, stringType, ""),
				field("task_id", "taskId", 5, stringType, ""),
				field("actor_id", "actorId", 6, stringType, ""),
				field("from_status_id", "fromStatusId", 7, stringType, ""),
				field("to_status_id", "toStatusId", 8, stringType, ""),
				field("occurred_at", "occurredAt", 9, messageType, ".google.protobuf.Timestamp"),
				field("payload_json", "payloadJson", 10, stringType, ""),
			}},
		},
		Service: []*descriptorpb.ServiceDescriptorProto{{
			Name: strptr("TaskEvents"),
			Method: []*descriptorpb.MethodDescriptorProto{{
				Name:            strptr("Subscribe"),
				InputType:       strptr(".taskflow.v1.SubscribeRequest"),
				OutputType:      strptr(".taskflow.v1.TaskEvent"),
				ServerStreaming: boolptr(true),
			}},
		}},
	}
	b, err := proto.Marshal(fd)
	if err != nil {
		panic(err)
	}
	return b
}

var file_taskflow_v1_task_events_proto_rawDesc = makeTaskEventsRawDescriptor()
var file_taskflow_v1_task_events_proto_rawDescOnce sync.Once
var file_taskflow_v1_task_events_proto_rawDescData = file_taskflow_v1_task_events_proto_rawDesc

func file_taskflow_v1_task_events_proto_rawDescGZIP() []byte {
	file_taskflow_v1_task_events_proto_rawDescOnce.Do(func() {
		file_taskflow_v1_task_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_taskflow_v1_task_events_proto_rawDescData)
	})
	return file_taskflow_v1_task_events_proto_rawDescData
}

var file_taskflow_v1_task_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_taskflow_v1_task_events_proto_goTypes = []interface{}{
	(*SubscribeRequest)(nil),
	(*TaskEvent)(nil),
	(*timestamppb.Timestamp)(nil),
}
var file_taskflow_v1_task_events_proto_depIdxs = []int32{
	2, // 0: taskflow.v1.TaskEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 1: taskflow.v1.TaskEvents.Subscribe:input_type -> taskflow.v1.SubscribeRequest
	1, // 2: taskflow.v1.TaskEvents.Subscribe:output_type -> taskflow.v1.TaskEvent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_taskflow_v1_task_events_proto_init() }
func file_taskflow_v1_task_events_proto_init() {
	if File_taskflow_v1_task_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taskflow_v1_task_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskflow_v1_task_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taskflow_v1_task_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskflow_v1_task_events_proto_goTypes,
		DependencyIndexes: file_taskflow_v1_task_events_proto_depIdxs,
		MessageInfos:      file_taskflow_v1_task_events_proto_msgTypes,
	}.Build()
	File_taskflow_v1_task_events_proto = out.File
	file_taskflow_v1_task_events_proto_rawDesc = nil
	file_taskflow_v1_task_events_proto_goTypes = nil
	file_taskflow_v1_task_events_proto_depIdxs = nil
}
