// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: taskflowv1/task_events.proto

package taskflowv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

const TaskEvents_Subscribe_FullMethodName = "/taskflow.v1.TaskEvents/Subscribe"

type TaskEventsClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (TaskEvents_SubscribeClient, error)
}

type taskEventsClient struct{ cc grpc.ClientConnInterface }

func NewTaskEventsClient(cc grpc.ClientConnInterface) TaskEventsClient {
	return &taskEventsClient{cc}
}

func (c *taskEventsClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (TaskEvents_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaskEvents_ServiceDesc.Streams[0], TaskEvents_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &taskEventsSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskEvents_SubscribeClient interface {
	Recv() (*TaskEvent, error)
	grpc.ClientStream
}

type taskEventsSubscribeClient struct{ grpc.ClientStream }

func (x *taskEventsSubscribeClient) Recv() (*TaskEvent, error) {
	m := new(TaskEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type TaskEventsServer interface {
	Subscribe(*SubscribeRequest, TaskEvents_SubscribeServer) error
	mustEmbedUnimplementedTaskEventsServer()
}

type UnimplementedTaskEventsServer struct{}

func (UnimplementedTaskEventsServer) Subscribe(*SubscribeRequest, TaskEvents_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTaskEventsServer) mustEmbedUnimplementedTaskEventsServer() {}

type UnsafeTaskEventsServer interface{ mustEmbedUnimplementedTaskEventsServer() }

func RegisterTaskEventsServer(s grpc.ServiceRegistrar, srv TaskEventsServer) {
	s.RegisterService(&TaskEvents_ServiceDesc, srv)
}

func _TaskEvents_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskEventsServer).Subscribe(m, &taskEventsSubscribeServer{stream})
}

type TaskEvents_SubscribeServer interface {
	Send(*TaskEvent) error
	grpc.ServerStream
}

type taskEventsSubscribeServer struct{ grpc.ServerStream }

func (x *taskEventsSubscribeServer) Send(m *TaskEvent) error { return x.ServerStream.SendMsg(m) }

var TaskEvents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskflow.v1.TaskEvents",
	HandlerType: (*TaskEventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{{
		StreamName:    "Subscribe",
		Handler:       _TaskEvents_Subscribe_Handler,
		ServerStreams: true,
	}},
	Metadata: "taskflowv1/task_events.proto",
}
